oss-slu/Pi4Micronaut

components/src/main/java/com/opensourcewithslu/components/controllers/SlideSwitchController.java, components/src/main/resources/application.yml, micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/SlideSwitchHelper.java
Created SlideSwitchHelper and SlideSwitchController, added config settings for the slide switch to yml file.
=> Slide Switch implementation

components/src/main/java/com/opensourcewithslu/components/controllers/RotaryEncoderController.java, components/src/main/resources/application.yml, micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/RotaryEncoderHelper.java, micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
Added support for Rotary Encoder on top of support for Push Button and Slide Switch. Small change to LED helper that makes our demo function properly but will most likely need to be reverted.
=> Traison rotary encoder

components/src/main/java/com/opensourcewithslu/components/controllers/RotaryEncoderController.java, components/src/main/java/com/opensourcewithslu/components/controllers/rgbController.java, components/src/main/resources/application.yml, micronautpi4j-utils/build.gradle, micronautpi4j-utils/src/main/java/com/opensourcewithslu/inputdevices/RotaryEncoderHelper.java, micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/RGBLEDHelper.java, micronautpi4j-utils/src/main/java/com/opensourcewithslu/utilities/MultiPinConfigs/DigitalInputMultiPinConfiguration.java, micronautpi4j-utils/src/main/java/com/opensourcewithslu/utilities/MultiPinConfigs/PwmMultiPinConfiguration.java, micronautpi4j-utils/src/main/java/com/opensourcewithslu/utilities/MultipinConfiguration.java, micronautpi4j-utils/src/main/java/com/opensourcewithslu/utilities/Pi4JMultipinFactory.java
Simplified multi pin components (RGB LED and Rotary Encoder) to be much easier to declare in application.yaml
=> Multi pin support

.github/workflows/asciidoc-build.yml, docs/index.adoc, docs/style.css
Styled Docs a bit better so the table of contents is now on the side of the page instead of the top. Extra headers are also on the docs at the moment to  show that the table of contents will scroll properly when exceeding the height of the window, these will be removed before deployment
=> More docs tests

feature_request_pi4M.md, issues_pi4M.md
Created templates per issue #55. Can update if templates are incorrect.
=> 55 issue templates

community-guidelines.md, micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/rgbLed.adoc, micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/RGBLEDHelper.java
=> Added documentation for RGB LED circuit guide. Issue 74

micronautpi4j-utils/build.gradle, micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/pushButton.adoc, micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc, micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/rotaryEncoder.adoc, micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/slideSwitch.adoc, micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/lcdScreen.adoc, micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/led.adoc, micronautpi4j-utils/src/docs/asciidoc/components/outputComponents/rgbLed.adoc
Change the include paths to go all the way back to the root before going to the file.
=> 75 fix unresolved directive documentation bug - take 2

components/src/main/java/com/opensourcewithslu/components/controllers/PushButtonController.java, components/src/main/resources/application.yml, micronautpi4j-utils/src/docs/asciidoc/components/inputComponents/pushButton.adoc, micronautpi4j-utils/src/main/java/com/opensourcewithslu/outputdevices/RGBLEDHelper.java
Need to fill in blanks and figure out if a YAML config is needed.
=> Completes Issue 83 and fixes bug with PushButtonController.

components/src/main/java/com/opensourcewithslu/components/controllers/LEDController.java
Added the LED Off and switch state endpoints to the controller for LED.
=> Fixes Issue #112

micronautpi4j-utils/src/main/java/com/opensourcewithslu/utilities/Pi4JFactory.java
=> fixes issue 111

micronautpi4j-utils/src/docs/asciidoc/style.css
Made preliminary changes to the .css file for easier readability. Will continue to read through the file and implement further changes. Also need to figure out how to view the changes.
=> Fixes #119

pi4micronaut-utils/build.gradle
Reverts oss-slu/Pi4Micronaut#164
=> Revert "Includes javadocs in the gh-pages branch"

pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/rfidScanner.adoc
Fixed unresolved directory bug for rfid. Closes Issue #75
=> fixed rfid adoc

README.md
Updated team memebers list to Readme.md
=> Updated team memebers list

.github/workflows/build-library-jar.yml
Reverted Back the workflow changes
=> Reverted Back the workflow changes

.github/workflows/build-library-jar.yml
Added github workflows into the build_library.yml file to make manually publish the library
=> Added github workflows into the build_library

.github/workflows/build-library-jar.yml
=> Revered the workflow changes

pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/MicroSwitchHelper.java, pi4micronaut-utils/src/test/java/com/opensourcewithslu/inputdevices/MicroSwitchHelperTests
Description:
Adds unit tests for the MicroSwitchHelper using JUnit 5 and Mockito, checking its initialization, state updates and event listener management. Also introduces logger injection to confirm the correct log message ('Initializing Micro Switch') is being produced.
What was changed:
In MicroSwitchHelper the logger was converted from static final to static with a new setLog(Logger newLog) method, this enables the use of a custom logger for testing.
Unit tests were implemented to verify initialization logic, state updates, and event listener management, and tests to confirm the expected log message.
How it was changed:
The logger in MicroSwitchHelper was changed from a static final to an instance level with the new setLog method. Unit tests were implemented using JUnit 5 and Mockito …
=> new pr for mirco switch helper tests w/ proper credentials

pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/SlideSwitchHelper.java, pi4micronaut-utils/src/test/java/com/opensourcewithslu/inputdevices/SlideSwitchHelperTest.java
Fixes #300 
Description:
This pull request adds comprehensive unit tests for the SlideSwitchHelper class to verify its functionality and robustness. The tests ensure that the helper correctly initializes its state, manages event listeners, and outputs the expected log messages.
What was changed:
Initialization Tests:
Added tests to verify that the isOn field is correctly set when the DigitalInput is high or low (testIsOnFieldSetCorrectlyWhenInputIsHigh and testIsOnFieldSetCorrectlyWhenInputIsLow).
Event Listener Management:
Implemented tests to confirm that the addEventListener and removeEventListener methods delegate correctly to the underlying DigitalInput (testAddEventListener and testRemoveEventListener).
Created a test (testCustomListenerInvocation) to ensure that custom event …
=> test(slide-switch): add comprehensive unit tests for SlideSwitchHelper

pi4micronaut-utils/src/main/java/com/opensourcewithslu/outputdevices/LEDHelper.java
Fixes #315 
What was changed: 
The project has been upgraded to Micronaut 4.7.6, and changes were made to the LEDHelper class to ensure its compatibility with the latest version. Singleton annotation was added, updated the logger declaration, and removed the setLog() method.
Why was it changed:
The Singleton design pattern will allow the framework to manage its lifecycle. Declaring the logger as final will ensure that the instance is only created once.  Lastly, removed the setLog() to prevent any runtime issues and due to the logger being immutable.
How it was changed:
The class was annotated with Singleton from jakarta.inject.Singleton to allow management by the Pi4Micronaut. The logger class was refactored to be a private static final field. The setLog() method was removed entirely. …
=> Upgraded LEDHelper.java

pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/PushButtonHelper.java
https://github.com/oss-slu/Pi4Micronaut/issues/317
What what changed:
I verified that the PushButtonHelper and DigitalInputConfiguration classes remain compatible with Micronaut 4.7.6. At the point there are no required code changed, as the classes do not directly depend on the Micronaut features that needed to be changed. Hardware testing was completed to ensure no functionalities changed with the update. 
Why it was changed:
Part of the Micronaut 4.7.6 upgraded all of these classes needed to be looked over to ensure compatibility. We needed to review the code to ensure that future updates do not bring undefined behavior.
How it was changed:
Reviewed PushButtonHelper and DigitalInputConfiguration for breaking changed in Micronaut 4.7.6, confirmed that all of the methods continue to be …
=> upgraded pushbuttonhhelper with micronaut 4.7.4

components/src/main/java/com/opensourcewithslu/components/controllers/MicroSwitchController.java, pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/MicroSwitchHelper.java, pi4micronaut-utils/src/test/java/com/opensourcewithslu/MicroSwitchHelperTests.java, pi4micronaut-utils/src/test/java/com/opensourcewithslu/MockDigitalInput.java
#329 
What what changed:
I updated MicroSwitchHelper and MicroSwitchController to verify they work with micronaut 4.7.6, and verified that there were no breaking changes in dependencies.
Why it was changed:
Part of the Micronaut 4.7.6 upgraded all of these classes needed to be looked over to ensure compatibility. We needed to review the code to ensure that future updates do not bring undefined behavior.
How it was changed:
Added the MicroSwitchHelper and Controller classes to the upgraded micronaut branch and tested from there to ensure they were still able to build with micronaut version 4.7.6. I then tested this updated version with hardware to ensure that functionalities and logging remained the same with these new updates. Below are videos to verify the functionalities remain the same …
=> Add MicroSwitchController and MicroSwitchHelper

components/src/main/java/com/opensourcewithslu/components/controllers/TiltSwitchController.java, pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/TiltSwitchHelper.java, pi4micronaut-utils/src/test/java/inputdevices/TiltSwitchHelperTests.java
Fixes #330
What was changed:
The TiltSwitchHelper class was upgraded to be compatible with Micronaut 4.7.6. The logging was enhanced to provide details when the tilt switch state changes. TiltSwitchController was added for testing and monitoring.
Why was it changed:
The upgrade to Micronaut 4.7.6 requires updated dependencies. The TiltSwitchHelper class will be utilized to make sure the state changes on the hardware is successful. Additionally, logging was added to help with any debugging issues.
How was it changed:
The TiltSwitchHelper class will function as a singleton within Micronaut's dependency injection framework. The event listener was refined to update the internal state and log changes when the state transitions. The new TiltSwitchController class was added to return a current …
=> Upgraded TiltSwitchHelper Class

components/src/main/java/com/opensourcewithslu/components/controllers/PIRSensorController.java, pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/PIRSensorHelper.java, pi4micronaut-utils/src/test/java/inputdevices/PIRSensorHelperTest.java
Fixes #336 
**What was changed:**
The PIRSensor class was upgraded to be compatible with Micronaut 4.7.6. A controller class was incorporated with the PIRSensor class to enable the toggling of the sensor monitoring and control of the RGB LED when motion is detected.
**Why was it changed:**
The upgrade to Micronaut 4.7.6 requires updated dependencies. The PIRSensor must accurately detect motion on the Raspberry PI to trigger LED changes.
**How was it changed:**
Additional log statements were implemented in the helper and controller class to capture state changes in the sensor and LED. The controller class was created to enable/disable the sensor and manage LED colors based on the inputs.
=> Upgraded PIRSensor

components/src/main/java/com/opensourcewithslu/components/controllers/UltraSonicSensorController.java, pi4micronaut-utils/src/main/java/com/opensourcewithslu/inputdevices/UltraSonicSensorHelper.java
Fix #337  
What was changed: Two files have been added for the helper and controller. These assist in testing the class for the latest version, as we previously had older versions.
Why was it changed: These changes are necessary because the classes are outdated, and we need to ensure we are running on the newest version.
How was it changed: The files I added are mostly the same as the previous version, so I copied those controllers and helpers from the main branch and pasted them to seyun_uss, but the directory addresses of each controller and helper were not accurate, so I modified them to the correct paths.
Key Components:
Setup Method (setUp):- Initializes a mock DigitalInput object.- Configures the mock to return false when isHigh is called.- Initializes the UltraSonicSensor object …
=> Fixed controllers and helper and succeesful Hardware Testing on Ultra Sonic Sensor
